# Configuration file for WebEssentials

# GUI
gui_title: '&5WebEssentials'

# URLs to be used by icons
vote_urls:
  - http://example.com/
  - http://example.com/
  - http://example.com/
website_urls:
  - http://example.com/
donate_urls:
  - http://example.com/
voice_server_urls:
  - '&6The IP of the voice server is: ts3.example.com'

# Vote Icon
vote_icon: PAPER
vote_icon_name: '&3Vote'
vote_icon_lore: '&6Vote for the server'
vote_icon_position: 0

# Website Icon
website_icon: PAPER
website_icon_name: '&3Website'
website_icon_lore: '&6Visit the server website'
website_icon_position: 1

# Donate Icon
donate_icon: PAPER
donate_icon_name: '&3Donate'
donate_icon_lore: '&6Donate to the server to keep it running'
donate_icon_position: 2

# Voice Server Icon
voice_server_icon: PAPER
voice_server_icon_name: '&3Voice Server'
voice_server_icon_lore: '&6Get the IP of the voice server'
voice_server_icon_position: 3